#!/bin/bash
#PBS -N nf-fastqc_1
#PBS -o /rdsgpfs/general/user/ywan1/home/qc/work/8a/87e42ddd68301a5637310d13e7f6b3/.command.log
#PBS -j oe
#PBS -l walltime=02:00:00
#PBS -lselect=1:ncpus=2:mem=4gb
cd /rdsgpfs/general/user/ywan1/home/qc/work/8a/87e42ddd68301a5637310d13e7f6b3

# NEXTFLOW TASK: fastqc (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /rdsgpfs/general/user/ywan1/home/qc/work/8a/87e42ddd68301a5637310d13e7f6b3/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /rdsgpfs/general/user/ywan1/home/qc/work/8a/87e42ddd68301a5637310d13e7f6b3/.command.begin
[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
# stage input files
rm -f ERR137805_1.fastq.gz
rm -f ERR137805_2.fastq.gz
ln -s /rdsgpfs/general/user/ywan1/home/qc/ERR137805_1.fastq.gz ERR137805_1.fastq.gz
ln -s /rdsgpfs/general/user/ywan1/home/qc/ERR137805_2.fastq.gz ERR137805_2.fastq.gz

set +e
ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
/bin/bash /rdsgpfs/general/user/ywan1/home/qc/work/8a/87e42ddd68301a5637310d13e7f6b3/.command.stub
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
